backend:
  name: github
  repo: TheFullResolution/thefullresolution

media_folder: static/assets
public_folder: assets

collections:
  - label: "Resume"
    name: "resume"
    file: "_content/resume.json"
    fields:
      - label: "Dev Experience"
        name: "dev_experience"
        fields:
          - {label: Title, name: title, widget: string}
          - label: Entry
            name: entry
            widget: list
            fields:
              - {label: Name, name: name, widget: string}
              - {label: Position, name: position, widget: string}
              - {label: Location, name: location, widget: string}
              - {label: Started, name: started, widget: date}
              - {label: Finished, name: finished, widget: date}
              - {label: "Technologies & Tools", name: technologies, widget: 'markdown'}
              - {label: "Accomplishments", name: accomplishments, widget: 'markdown'}

