backend:
  name: github
  repo: TheFullResolution/thefullresolution

media_folder: static/assets
public_folder: assets

collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "Resume"
        name: "resume"
        file: "_content/resume.json"
        fields:
          - label: "Section"
            name: section
            widget: list
            fields:
              - {label: Title, name: title, widget: string}
              - label: "content"
                name: content
                widget: list
                fields:
                  - {label: Name, name: name, widget: string}
                  - {label: Url, name: url, widget: string, required: false}
                  - {label: Description, name: description, widget: markdown, required: false}
                  - {label: Position, name: position, widget: string, required: false}
                  - {label: Location, name: location, widget: string, required: false}
                  - {label: Started, name: started, widget: date}
                  - {label: Finished, name: finished, widget: date}
                  - {label: "Technologies & Tools", name: technologies, widget: markdown, required: false}
                  - {label: "Accomplishments", name: accomplishments, widget: markdown, required: false}

